// Labelled SAMPLE data. Used only when GET /api/state fails. Dates are
// frozen at 2026-09-08 18:46 America/Los_Angeles (ISO week 2026-W37), and every
// phone number is already masked, exactly as the server would send it.

export const SAMPLE_STATE = {
 "mode": "dry-run",
 "now": "2026-09-09T01:46:12.000Z",
 "localNow": {
  "timezone": "America/Los_Angeles",
  "isoWeekday": 2,
  "minutesOfDay": 1126,
  "hhmm": "18:46"
 },
 "window": {
  "start": "10:00",
  "end": "17:00",
  "days": [
   1,
   2,
   3,
   4,
   5,
   6
  ]
 },
 "week": "2026-W37",
 "callerName": "Shortline",
 "operatorName": "Maya",
 "watches": [
  {
   "id": "amoxicillin-susp",
   "product": {
    "name": "amoxicillin",
    "strength": "400 mg/5 mL",
    "form": "oral suspension"
   },
   "status": "active",
   "regions": [
    "US-CA-SF",
    "US-CA-EB",
    "US-CA-SJ"
   ]
  },
  {
   "id": "methylphenidate-er",
   "product": {
    "name": "methylphenidate ER",
    "strength": "36 mg",
    "form": "tablets"
   },
   "status": "paused",
   "regions": [
    "US-CA-SF",
    "US-CA-EB",
    "US-CA-SJ"
   ]
  }
 ],
 "watch": {
  "id": "amoxicillin-susp",
  "product": {
   "name": "amoxicillin",
   "strength": "400 mg/5 mL",
   "form": "oral suspension"
  },
  "regions": [
   "US-CA-SF",
   "US-CA-EB",
   "US-CA-SJ"
  ],
  "panelPerStratum": 3,
  "cooldownDays": 14,
  "globalMinGapDays": 5,
  "window": {
   "start": "10:00",
   "end": "17:00",
   "days": [
    1,
    2,
    3,
    4,
    5,
    6
   ]
  },
  "thresholds": {
   "shortageUpper": 0.5,
   "strainedPoint": 0.7
  },
  "minUsable": 6,
  "status": "active",
  "createdAt": "2026-09-09T23:43:41.218Z"
 },
 "estimates": [
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W29",
   "computedAt": "2026-07-15T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 3,
     "available": 2,
     "inStock": 1,
     "limited": 1,
     "pHat": 0.6666666666666666,
     "low": 0.2076595988078242,
     "high": 0.9385080559790691
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 2,
     "inStock": 2,
     "limited": 0,
     "pHat": 1,
     "low": 0.3423802239546494,
     "high": 1
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 1,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 2,
     "inStock": 2,
     "limited": 0,
     "pHat": 1,
     "low": 0.3423802239546494,
     "high": 1
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.8,
    "low": 0.4901624691221323,
    "high": 0.9433178490622331,
    "nEff": 10
   },
   "coverage": 0.8285714285714286,
   "planned": 18,
   "usable": 10,
   "responseRate": 0.5555555555555556,
   "signal": "available",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W30",
   "computedAt": "2026-07-22T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 2,
     "inStock": 1,
     "limited": 1,
     "pHat": 1,
     "low": 0.3423802239546494,
     "high": 1
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 3,
     "available": 2,
     "inStock": 2,
     "limited": 0,
     "pHat": 0.6666666666666666,
     "low": 0.2076595988078242,
     "high": 0.9385080559790691
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 2,
     "inStock": 2,
     "limited": 0,
     "pHat": 1,
     "low": 0.3423802239546494,
     "high": 1
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 0,
     "limited": 1,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.6666666666666666,
    "low": 0.3906220869404939,
    "high": 0.86187990987514,
    "nEff": 12
   },
   "coverage": 1,
   "planned": 18,
   "usable": 12,
   "responseRate": 0.6666666666666666,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W31",
   "computedAt": "2026-07-29T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 1,
     "available": 1,
     "inStock": 0,
     "limited": 1,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 1,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.6,
    "low": 0.3126737679211953,
    "high": 0.831819671473593,
    "nEff": 10
   },
   "coverage": 1,
   "planned": 15,
   "usable": 10,
   "responseRate": 0.6666666666666666,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W32",
   "computedAt": "2026-08-05T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 3,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.3333333333333333,
     "low": 0.06149194402093078,
     "high": 0.7923404011921757
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 1,
     "available": 1,
     "inStock": 0,
     "limited": 1,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 3,
     "available": 2,
     "inStock": 1,
     "limited": 1,
     "pHat": 0.6666666666666666,
     "low": 0.2076595988078242,
     "high": 0.9385080559790691
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.5,
    "low": 0.25378159616252394,
    "high": 0.7462184038374761,
    "nEff": 12
   },
   "coverage": 1,
   "planned": 17,
   "usable": 12,
   "responseRate": 0.7058823529411765,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W33",
   "computedAt": "2026-08-12T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 1,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.3333333333333333,
    "low": 0.12058381743407343,
    "high": 0.6457978664749412,
    "nEff": 9
   },
   "coverage": 0.8235294117647058,
   "planned": 14,
   "usable": 9,
   "responseRate": 0.6428571428571429,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W34",
   "computedAt": "2026-08-19T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 1,
     "inStock": 0,
     "limited": 1,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 2,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.5,
     "low": 0.09453120463920084,
     "high": 0.9054687953607992
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 3,
     "available": 2,
     "inStock": 1,
     "limited": 1,
     "pHat": 0.6666666666666666,
     "low": 0.2076595988078242,
     "high": 0.9385080559790691
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.3333333333333333,
    "low": 0.13812009012485987,
    "high": 0.6093779130595061,
    "nEff": 12
   },
   "coverage": 1,
   "planned": 16,
   "usable": 12,
   "responseRate": 0.75,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W35",
   "computedAt": "2026-08-26T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 3,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 0.3333333333333333,
     "low": 0.06149194402093078,
     "high": 0.7923404011921757
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 1,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 1,
     "low": 0.2065493117918027,
     "high": 1
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 1,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.2222222222222222,
    "low": 0.06322510654056959,
    "high": 0.5474110333077882,
    "nEff": 9
   },
   "coverage": 1,
   "planned": 13,
   "usable": 9,
   "responseRate": 0.6923076923076923,
   "signal": "strained",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W36",
   "computedAt": "2026-09-02T23:43:41.220Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 3,
     "usable": 3,
     "available": 1,
     "inStock": 0,
     "limited": 1,
     "pHat": 0.3333333333333333,
     "low": 0.06149194402093078,
     "high": 0.7923404011921757
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 3,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 2,
     "usable": 1,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.7934506882081973
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 2,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 3,
     "usable": 2,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": 0,
     "low": 0,
     "high": 0.6576197760453506
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 0.08333333333333333,
    "low": 0.014865094239669363,
    "high": 0.35387991372124555,
    "nEff": 12
   },
   "coverage": 1,
   "planned": 16,
   "usable": 12,
   "responseRate": 0.75,
   "signal": "shortage",
   "simulated": true
  },
  {
   "watchId": "amoxicillin-susp",
   "isoWeek": "2026-W37",
   "computedAt": "2026-09-09T01:40:00.000Z",
   "strata": [
    {
     "stratum": "US-CA-EB|chain",
     "region": "US-CA-EB",
     "kind": "chain",
     "frameSize": 6,
     "planned": 0,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-EB|independent",
     "region": "US-CA-EB",
     "kind": "independent",
     "frameSize": 6,
     "planned": 1,
     "usable": 1,
     "available": 1,
     "inStock": 1,
     "limited": 0,
     "pHat": 1.0,
     "low": 0.2065,
     "high": 1.0
    },
    {
     "stratum": "US-CA-SF|chain",
     "region": "US-CA-SF",
     "kind": "chain",
     "frameSize": 6,
     "planned": 0,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-SF|independent",
     "region": "US-CA-SF",
     "kind": "independent",
     "frameSize": 5,
     "planned": 0,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-SJ|chain",
     "region": "US-CA-SJ",
     "kind": "chain",
     "frameSize": 6,
     "planned": 0,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    },
    {
     "stratum": "US-CA-SJ|independent",
     "region": "US-CA-SJ",
     "kind": "independent",
     "frameSize": 5,
     "planned": 0,
     "usable": 0,
     "available": 0,
     "inStock": 0,
     "limited": 0,
     "pHat": null,
     "low": null,
     "high": null
    }
   ],
   "method": "pooled_wilson",
   "overall": {
    "pHat": 1.0,
    "low": 0.2065,
    "high": 1.0,
    "nEff": 1
   },
   "coverage": 0.17,
   "planned": 1,
   "usable": 1,
   "responseRate": null,
   "signal": "insufficient_data",
   "simulated": false
  }
 ],
 "sweep": {
  "id": "swp_sample37",
  "isoWeek": "2026-W37",
  "status": "planned",
  "planned": 16,
  "dispatched": 0,
  "verified": 0,
  "waitingForWindow": 16,
  "inFlight": 0,
  "needsHuman": 1,
  "undersampled": [
   "US-CA-SF|independent"
  ],
  "plannedSites": [
   {
    "id": "eb-chn-2",
    "name": "Bayline Pharmacy #102",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-chn-5",
    "name": "Pacific Care Pharmacy #105",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-chn-1",
    "name": "Presidio Drug #101",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-chn-4",
    "name": "Redwood Wellness Drug #104",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-chn-6",
    "name": "Summit Drugstore #106",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-5",
    "name": "Alameda Island Pharmacy",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-6",
    "name": "Berkeley Hills Drug",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-3",
    "name": "Fruitvale Botica",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-1",
    "name": "Lakeshore Pharmacy",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-4",
    "name": "Rockridge Apothecary",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "eb-ind-2",
    "name": "Temescal Family Rx",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "sf-chn-2",
    "name": "Bayline Pharmacy #102",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "sf-chn-3",
    "name": "Crescent Rx #103",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "sf-chn-5",
    "name": "Pacific Care Pharmacy #105",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "sf-chn-1",
    "name": "Presidio Drug #101",
    "dispatched": false,
    "verified": false
   },
   {
    "id": "sf-chn-4",
    "name": "Redwood Wellness Drug #104",
    "dispatched": false,
    "verified": false
   }
  ]
 },
 "dispatches": [
    {
      "id": "dsp_sample_needs_human",
      "kind": "sweep",
      "state": "needs_human",
      "callId": null,
      "siteIds": ["sj-chn-4"],
      "siteNames": ["Summit Drugstore #106"],
      "waveIndex": null,
      "sweepId": "swp_sample37",
      "findRequestId": null,
      "createdAt": "2026-09-09T17:02:11.000Z",
      "submittedAt": null,
      "terminalAt": null,
      "note": "CALL-E did not acknowledge the task within 20 minutes; reconcile before re-dialling",
      "simulated": true
    },
    {
   "id": "dsp_sample_f2",
   "kind": "find",
   "state": "needs_human",
   "callId": null,
   "siteIds": [
    "sf-chn-3"
   ],
   "siteNames": [
    "Crescent Rx #103"
   ],
   "waveIndex": 0,
   "sweepId": null,
   "findRequestId": "fr_sample_human",
   "createdAt": "2026-09-08T22:04:00.000Z",
   "submittedAt": "2026-09-08T22:04:01.000Z",
   "terminalAt": null,
   "note": "CALL-E did not acknowledge the task within 20 minutes",
   "simulated": true
  },
  {
   "id": "dsp_sample_f1",
   "kind": "find",
   "state": "terminal_verified",
   "callId": "call_fake_sample01",
   "siteIds": [
    "eb-ind-3",
    "eb-ind-5"
   ],
   "siteNames": [
    "Fruitvale Botica",
    "Alameda Island Pharmacy"
   ],
   "waveIndex": 0,
   "sweepId": null,
   "findRequestId": "fr_sample_met",
   "createdAt": "2026-09-09T01:38:30.000Z",
   "submittedAt": "2026-09-09T01:38:31.000Z",
   "terminalAt": "2026-09-09T01:39:40.000Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_aff38507be46b2e3",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_139c2b7ddb15",
   "siteIds": [
    "eb-chn-5",
    "eb-chn-4",
    "eb-chn-2",
    "eb-ind-3",
    "eb-ind-5",
    "eb-ind-1"
   ],
   "siteNames": [
    "Pacific Care Pharmacy #105",
    "Redwood Wellness Drug #104",
    "Bayline Pharmacy #102",
    "Fruitvale Botica",
    "Alameda Island Pharmacy",
    "Lakeshore Pharmacy"
   ],
   "waveIndex": null,
   "sweepId": "swp_ca0e8fea902593dc",
   "findRequestId": null,
   "createdAt": "2026-09-02T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.625Z",
   "terminalAt": "2026-09-09T23:43:41.631Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_2f8a742954992b2b",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_11d69879485d",
   "siteIds": [
    "sf-chn-2",
    "sf-chn-4",
    "sf-chn-1",
    "sf-ind-2",
    "sf-ind-1",
    "sj-chn-2"
   ],
   "siteNames": [
    "Bayline Pharmacy #102",
    "Redwood Wellness Drug #104",
    "Presidio Drug #101",
    "Golden Gate Apothecary",
    "Mission Family Pharmacy",
    "Bayline Pharmacy #102"
   ],
   "waveIndex": null,
   "sweepId": "swp_ca0e8fea902593dc",
   "findRequestId": null,
   "createdAt": "2026-09-02T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.627Z",
   "terminalAt": "2026-09-09T23:43:41.640Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_82df1750c0b52fe3",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_122e39d0db9a",
   "siteIds": [
    "sj-chn-3",
    "sj-ind-3",
    "sj-ind-6",
    "sj-ind-1"
   ],
   "siteNames": [
    "Crescent Rx #103",
    "Japantown Drug",
    "Almaden Valley Rx",
    "Willow Glen Pharmacy"
   ],
   "waveIndex": null,
   "sweepId": "swp_ca0e8fea902593dc",
   "findRequestId": null,
   "createdAt": "2026-09-02T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.628Z",
   "terminalAt": "2026-09-09T23:43:41.649Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_7a04dbc7e6a2f15f",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_54a6afc5148c",
   "siteIds": [
    "eb-chn-3",
    "eb-chn-6",
    "eb-chn-1",
    "eb-ind-4",
    "eb-ind-6",
    "eb-ind-2"
   ],
   "siteNames": [
    "Crescent Rx #103",
    "Summit Drugstore #106",
    "Presidio Drug #101",
    "Rockridge Apothecary",
    "Berkeley Hills Drug",
    "Temescal Family Rx"
   ],
   "waveIndex": null,
   "sweepId": "swp_b692141868045553",
   "findRequestId": null,
   "createdAt": "2026-08-26T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.588Z",
   "terminalAt": "2026-09-09T23:43:41.593Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_7f1851f73ac3401f",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_9ce07f82f69e",
   "siteIds": [
    "sf-chn-5",
    "sf-chn-3",
    "sf-ind-6",
    "sf-ind-5",
    "sj-chn-1",
    "sj-ind-4"
   ],
   "siteNames": [
    "Pacific Care Pharmacy #105",
    "Crescent Rx #103",
    "Richmond District Pharmacy",
    "Bayview Community Drug",
    "Presidio Drug #101",
    "Santa Clara Apothecary"
   ],
   "waveIndex": null,
   "sweepId": "swp_b692141868045553",
   "findRequestId": null,
   "createdAt": "2026-08-26T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.589Z",
   "terminalAt": "2026-09-09T23:43:41.602Z",
   "note": null,
   "simulated": true
  },
  {
   "id": "dsp_c3b1721169640c35",
   "kind": "sweep",
   "state": "terminal_verified",
   "callId": "call_fake_fd2c87ef2aca",
   "siteIds": [
    "sj-ind-2"
   ],
   "siteNames": [
    "Alum Rock Family Rx"
   ],
   "waveIndex": null,
   "sweepId": "swp_b692141868045553",
   "findRequestId": null,
   "createdAt": "2026-08-26T23:43:41.220Z",
   "submittedAt": "2026-09-09T23:43:41.590Z",
   "terminalAt": "2026-09-09T23:43:41.608Z",
   "note": null,
   "simulated": true
  }
 ],
 "observations": [
  {
   "id": "obs_sample_found",
   "watchId": "amoxicillin-susp",
   "findRequestId": "fr_sample_met",
   "siteId": "eb-ind-3",
   "dispatchId": "dsp_sample_f1",
   "callId": "call_fake_sample01",
   "recipientId": "rcp_sample01",
   "source": "find",
   "observedAt": "2026-09-09T01:39:30.000Z",
   "outcome": "in_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "",
   "quantityNote": "two bottles",
   "evidenceQuote": "yes, we have two bottles of the 400 on the shelf",
   "taskConfidenceScore": 0.93,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "offered",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 8,
   "siteName": "Fruitvale Botica"
  },
  {
   "id": "obs_sample_vm",
   "watchId": "amoxicillin-susp",
   "findRequestId": "fr_sample_met",
   "siteId": "eb-ind-5",
   "dispatchId": "dsp_sample_f1",
   "callId": "call_fake_sample01",
   "recipientId": "rcp_sample02",
   "source": "find",
   "observedAt": "2026-09-09T01:39:10.000Z",
   "outcome": "voicemail",
   "answeredBy": "voicemail",
   "reachedPharmacy": "no",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": null,
   "taskConfidenceLabel": null,
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "voicemail",
   "simulated": true,
   "transcriptTurns": 0,
   "siteName": "Alameda Island Pharmacy"
  },
  {
   "id": "obs_sample_prog",
   "watchId": "amoxicillin-susp",
   "findRequestId": "fr_sample_human",
   "siteId": "sf-chn-3",
   "dispatchId": "dsp_sample_f2",
   "callId": "call_fake_sample02",
   "recipientId": "rcp_sample03",
   "source": "find",
   "observedAt": "2026-09-08T22:05:00.000Z",
   "outcome": "unknown",
   "answeredBy": "unknown",
   "reachedPharmacy": "unknown",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": null,
   "taskConfidenceLabel": null,
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "recipient_in_progress",
   "simulated": true,
   "transcriptTurns": 0,
   "siteName": "Crescent Rx #103"
  },
  {
   "id": "obs_sample_ex1",
   "watchId": "amoxicillin-susp",
   "findRequestId": "fr_sample_exh",
   "siteId": "sj-ind-2",
   "dispatchId": "dsp_sample_f3",
   "callId": "call_fake_sample03",
   "recipientId": "rcp_sample04",
   "source": "find",
   "observedAt": "2026-09-08T19:12:00.000Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "maybe Thursday",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.9,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 6,
   "siteName": "Alum Rock Family Rx"
  },
  {
   "id": "obs_sample_ex2",
   "watchId": "amoxicillin-susp",
   "findRequestId": "fr_sample_exh",
   "siteId": "sj-ind-3",
   "dispatchId": "dsp_sample_f4",
   "callId": "call_fake_sample04",
   "recipientId": "rcp_sample05",
   "source": "find",
   "observedAt": "2026-09-08T19:20:00.000Z",
   "outcome": "ivr_dead_end",
   "answeredBy": "ivr",
   "reachedPharmacy": "no",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": null,
   "taskConfidenceLabel": null,
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "ivr_only",
   "simulated": true,
   "transcriptTurns": 3,
   "siteName": "Japantown Drug"
  },
  {
   "id": "obs_d53e344c2f00dd53",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-ind-1",
   "dispatchId": "dsp_82df1750c0b52fe3",
   "callId": "call_fake_122e39d0db9a",
   "recipientId": "rcp_d9dcc60d",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "refused",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "we can't give out stock information over the phone",
   "taskConfidenceScore": 1,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "refused",
   "simulated": true,
   "transcriptTurns": 5,
   "siteName": "Willow Glen Pharmacy"
  },
  {
   "id": "obs_3584dd89bdd88245",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-ind-6",
   "dispatchId": "dsp_82df1750c0b52fe3",
   "callId": "call_fake_122e39d0db9a",
   "recipientId": "rcp_edcb19bd",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 1,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Almaden Valley Rx"
  },
  {
   "id": "obs_c18490630086c2c1",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-ind-3",
   "dispatchId": "dsp_82df1750c0b52fe3",
   "callId": "call_fake_122e39d0db9a",
   "recipientId": "rcp_2779c344",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 1,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Japantown Drug"
  },
  {
   "id": "obs_0bf1112eefb77300",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-chn-3",
   "dispatchId": "dsp_82df1750c0b52fe3",
   "callId": "call_fake_122e39d0db9a",
   "recipientId": "rcp_a26e57a1",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 1,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Crescent Rx #103"
  },
  {
   "id": "obs_3ba9b9c88cb4306e",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-chn-2",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_80607705",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Bayline Pharmacy #102"
  },
  {
   "id": "obs_97139b41dab5550d",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-ind-1",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_ba5b6187",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "unreachable",
   "answeredBy": "unknown",
   "reachedPharmacy": "unknown",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "recipient_failed",
   "simulated": true,
   "transcriptTurns": 0,
   "siteName": "Mission Family Pharmacy"
  },
  {
   "id": "obs_e9eb5dc7d399f7bb",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-ind-2",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_199819e8",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Golden Gate Apothecary"
  },
  {
   "id": "obs_5a71991996c7e406",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-chn-1",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_b22aa842",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Presidio Drug #101"
  },
  {
   "id": "obs_dfe411bed19b8828",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-chn-4",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_e5613aad",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "voicemail",
   "answeredBy": "voicemail",
   "reachedPharmacy": "no",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "voicemail",
   "simulated": true,
   "transcriptTurns": 1,
   "siteName": "Redwood Wellness Drug #104"
  },
  {
   "id": "obs_ae6cf753a1d9c935",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-chn-2",
   "dispatchId": "dsp_2f8a742954992b2b",
   "callId": "call_fake_11d69879485d",
   "recipientId": "rcp_14cf17c1",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.67,
   "taskConfidenceLabel": "medium",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Bayline Pharmacy #102"
  },
  {
   "id": "obs_4296566f6cf74ffd",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-ind-1",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_c826cb38",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Lakeshore Pharmacy"
  },
  {
   "id": "obs_1af8bd4e80c53e09",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-ind-5",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_e949f321",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Alameda Island Pharmacy"
  },
  {
   "id": "obs_471b9ffb54412866",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-ind-3",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_ff355c91",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "limited",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "Thursday's delivery",
   "quantityNote": "a couple of bottles left",
   "evidenceQuote": "we only have a couple of bottles left",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Fruitvale Botica"
  },
  {
   "id": "obs_487ca6635ed21970",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-chn-2",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_296c9653",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "ivr_dead_end",
   "answeredBy": "ivr",
   "reachedPharmacy": "no",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "ivr_only",
   "simulated": true,
   "transcriptTurns": 3,
   "siteName": "Bayline Pharmacy #102"
  },
  {
   "id": "obs_1287b5de0b8e0325",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-chn-4",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_96d551e4",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Redwood Wellness Drug #104"
  },
  {
   "id": "obs_736ff2c4b106bde9",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "eb-chn-5",
   "dispatchId": "dsp_aff38507be46b2e3",
   "callId": "call_fake_139c2b7ddb15",
   "recipientId": "rcp_c202a8b5",
   "source": "sweep",
   "observedAt": "2026-09-02T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Pacific Care Pharmacy #105"
  },
  {
   "id": "obs_9029e2922cabe81d",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-ind-2",
   "dispatchId": "dsp_c3b1721169640c35",
   "callId": "call_fake_fd2c87ef2aca",
   "recipientId": "rcp_d71c02c7",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 1,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Alum Rock Family Rx"
  },
  {
   "id": "obs_56bad0b262d962a9",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-ind-4",
   "dispatchId": "dsp_7f1851f73ac3401f",
   "callId": "call_fake_9ce07f82f69e",
   "recipientId": "rcp_42773c35",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Santa Clara Apothecary"
  },
  {
   "id": "obs_7b83888758cfef83",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sj-chn-1",
   "dispatchId": "dsp_7f1851f73ac3401f",
   "callId": "call_fake_9ce07f82f69e",
   "recipientId": "rcp_cebad3d8",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "out_of_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "no idea, it's on backorder",
   "quantityNote": "",
   "evidenceQuote": "we're completely out",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 7,
   "siteName": "Presidio Drug #101"
  },
  {
   "id": "obs_7a01fcddc01c15b3",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-ind-5",
   "dispatchId": "dsp_7f1851f73ac3401f",
   "callId": "call_fake_9ce07f82f69e",
   "recipientId": "rcp_7c4eb9c6",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "voicemail",
   "answeredBy": "voicemail",
   "reachedPharmacy": "no",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "voicemail",
   "simulated": true,
   "transcriptTurns": 1,
   "siteName": "Bayview Community Drug"
  },
  {
   "id": "obs_cbc0f3cf4d12ed4b",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-ind-6",
   "dispatchId": "dsp_7f1851f73ac3401f",
   "callId": "call_fake_9ce07f82f69e",
   "recipientId": "rcp_6ba15eb6",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "in_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "yep, we've got it on the shelf",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": true,
   "usableReason": "verified",
   "simulated": true,
   "transcriptTurns": 9,
   "siteName": "Richmond District Pharmacy"
  },
  {
   "id": "obs_39d8ce7629031d1e",
   "watchId": "amoxicillin-susp",
   "findRequestId": null,
   "siteId": "sf-chn-3",
   "dispatchId": "dsp_7f1851f73ac3401f",
   "callId": "call_fake_9ce07f82f69e",
   "recipientId": "rcp_d7ed3595",
   "source": "sweep",
   "observedAt": "2026-08-26T23:43:41.220Z",
   "outcome": "in_stock",
   "answeredBy": "human",
   "reachedPharmacy": "yes",
   "restockExpectation": "",
   "quantityNote": "",
   "evidenceQuote": "plenty on hand, no problem at all",
   "taskConfidenceScore": 0.83,
   "taskConfidenceLabel": "high",
   "doNotCallRequest": false,
   "holdResponse": "not_asked",
   "usable": false,
   "usableReason": "evidence_unattributed",
   "simulated": true,
   "transcriptTurns": 5,
   "siteName": "Crescent Rx #103"
  }
 ],
 "sites": [
  {
   "id": "eb-chn-2",
   "name": "Bayline Pharmacy #102",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0114",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "ivr_dead_end",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7694,
   "lng": -122.2194
  },
  {
   "id": "eb-chn-3",
   "name": "Crescent Rx #103",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0115",
   "optOut": true,
   "optOutReason": "dashboard",
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7489,
   "lng": -122.2569
  },
  {
   "id": "eb-chn-5",
   "name": "Pacific Care Pharmacy #105",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0117",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8076,
   "lng": -122.34
  },
  {
   "id": "eb-chn-1",
   "name": "Presidio Drug #101",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0113",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7431,
   "lng": -122.3312
  },
  {
   "id": "eb-chn-4",
   "name": "Redwood Wellness Drug #104",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0116",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8222,
   "lng": -122.2904
  },
  {
   "id": "eb-chn-6",
   "name": "Summit Drugstore #106",
   "kind": "chain",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0118",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "in_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7295,
   "lng": -122.317
  },
  {
   "id": "eb-ind-5",
   "name": "Alameda Island Pharmacy",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0123",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7591,
   "lng": -122.2581
  },
  {
   "id": "eb-ind-6",
   "name": "Berkeley Hills Drug",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0124",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "in_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.804,
   "lng": -122.21
  },
  {
   "id": "eb-ind-3",
   "name": "Fruitvale Botica",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0121",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "limited",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7925,
   "lng": -122.302
  },
  {
   "id": "eb-ind-1",
   "name": "Lakeshore Pharmacy",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0119",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8289,
   "lng": -122.2816
  },
  {
   "id": "eb-ind-4",
   "name": "Rockridge Apothecary",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0122",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8471,
   "lng": -122.2382
  },
  {
   "id": "eb-ind-2",
   "name": "Temescal Family Rx",
   "kind": "independent",
   "region": "US-CA-EB",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 510 ••• 0120",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": "2026-08-26T23:43:41.220Z",
   "lat": 37.7703,
   "lng": -122.2563
  },
  {
   "id": "sf-chn-2",
   "name": "Bayline Pharmacy #102",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0102",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7851,
   "lng": -122.4628
  },
  {
   "id": "sf-chn-3",
   "name": "Crescent Rx #103",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0103",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "in_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7736,
   "lng": -122.4334
  },
  {
   "id": "sf-chn-5",
   "name": "Pacific Care Pharmacy #105",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0105",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7237,
   "lng": -122.4266
  },
  {
   "id": "sf-chn-1",
   "name": "Presidio Drug #101",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0101",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7524,
   "lng": -122.4549
  },
  {
   "id": "sf-chn-4",
   "name": "Redwood Wellness Drug #104",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0104",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "voicemail",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7258,
   "lng": -122.4193
  },
  {
   "id": "sf-chn-6",
   "name": "Summit Drugstore #106",
   "kind": "chain",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0106",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-07-15T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": "2026-07-15T23:43:41.220Z",
   "lat": 37.727,
   "lng": -122.4609
  },
  {
   "id": "sf-ind-5",
   "name": "Bayview Community Drug",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0111",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "voicemail",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8176,
   "lng": -122.4653
  },
  {
   "id": "sf-ind-2",
   "name": "Golden Gate Apothecary",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0108",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7324,
   "lng": -122.4477
  },
  {
   "id": "sf-ind-1",
   "name": "Mission Family Pharmacy",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0107",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "unreachable",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7625,
   "lng": -122.3873
  },
  {
   "id": "sf-ind-4",
   "name": "Noe Valley Pharmacy",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0110",
   "optOut": true,
   "optOutReason": "asked on call call_fake_9831925bd671",
   "lastOutcome": "unknown",
   "lastObservedAt": "2026-07-15T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": null,
   "lat": 37.7777,
   "lng": -122.4303
  },
  {
   "id": "sf-ind-6",
   "name": "Richmond District Pharmacy",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0112",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "in_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.8058,
   "lng": -122.441
  },
  {
   "id": "sf-ind-3",
   "name": "Sunset Neighborhood Rx",
   "kind": "independent",
   "region": "US-CA-SF",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 415 ••• 0109",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-08-05T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": "2026-08-05T23:43:41.220Z",
   "lat": 37.7827,
   "lng": -122.3752
  },
  {
   "id": "sj-chn-2",
   "name": "Bayline Pharmacy #102",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0126",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.4264,
   "lng": -121.9587,
   "testLine": true
  },
  {
   "id": "sj-chn-3",
   "name": "Crescent Rx #103",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0127",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.3253,
   "lng": -121.8437
  },
  {
   "id": "sj-chn-5",
   "name": "Pacific Care Pharmacy #105",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0129",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-08-12T23:43:41.220Z",
   "callsThisMonth": 1,
   "carries": true,
   "refusedAt": "2026-08-12T23:43:41.220Z",
   "lat": 37.2571,
   "lng": -121.8597
  },
  {
   "id": "sj-chn-1",
   "name": "Presidio Drug #101",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0125",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.3813,
   "lng": -121.9282
  },
  {
   "id": "sj-chn-4",
   "name": "Redwood Wellness Drug #104",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0128",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-07-15T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": "2026-07-15T23:43:41.220Z",
   "lat": 37.2774,
   "lng": -121.892
  },
  {
   "id": "sj-chn-6",
   "name": "Summit Drugstore #106",
   "kind": "chain",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0130",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-07-22T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": "2026-07-22T23:43:41.220Z",
   "lat": 37.3876,
   "lng": -121.8769
  },
  {
   "id": "sj-ind-6",
   "name": "Almaden Valley Rx",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0136",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.2609,
   "lng": -121.8537
  },
  {
   "id": "sj-ind-2",
   "name": "Alum Rock Family Rx",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0132",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.3752,
   "lng": -121.873
  },
  {
   "id": "sj-ind-3",
   "name": "Japantown Drug",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0133",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.3544,
   "lng": -121.8979
  },
  {
   "id": "sj-ind-4",
   "name": "Santa Clara Apothecary",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0134",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "out_of_stock",
   "lastObservedAt": "2026-08-26T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": null,
   "lat": 37.4012,
   "lng": -121.81
  },
  {
   "id": "sj-ind-5",
   "name": "Sunnyvale Neighborhood Pharmacy",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0135",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "not_reached",
   "lastObservedAt": "2026-07-29T23:43:41.220Z",
   "callsThisMonth": 0,
   "carries": true,
   "refusedAt": null,
   "lat": 37.3353,
   "lng": -121.8605
  },
  {
   "id": "sj-ind-1",
   "name": "Willow Glen Pharmacy",
   "kind": "independent",
   "region": "US-CA-SJ",
   "timezone": "America/Los_Angeles",
   "phoneMasked": "+1 408 ••• 0131",
   "optOut": false,
   "optOutReason": null,
   "lastOutcome": "refused",
   "lastObservedAt": "2026-09-02T23:43:41.220Z",
   "callsThisMonth": 2,
   "carries": true,
   "refusedAt": "2026-09-02T23:43:41.220Z",
   "lat": 37.4076,
   "lng": -121.9235
  }
 ],
 "finds": [
  {
   "request": {
    "id": "fr_sample_met",
    "watchId": "amoxicillin-susp",
    "product": {
     "name": "amoxicillin",
     "strength": "400 mg/5 mL",
     "form": "oral suspension"
    },
    "region": "US-CA-EB",
    "need": 1,
    "waveSize": 3,
    "maxWaves": 2,
    "askHold": true,
    "status": "met",
    "plannedSiteIds": [
     "eb-ind-3",
     "eb-ind-5"
    ],
    "usedSiteIds": [
     "eb-ind-3",
     "eb-ind-5"
    ],
    "confirmedSiteIds": [
     "eb-ind-3"
    ],
    "createdAt": "2026-09-09T01:38:00.000Z",
    "updatedAt": "2026-09-09T01:39:40.000Z"
   },
   "productLabel": "amoxicillin 400 mg/5 mL oral suspension",
   "waves": 1,
   "halt": null,
   "confirmed": [
    {
     "siteId": "eb-ind-3",
     "name": "Fruitvale Botica",
     "phoneMasked": "+1 510 ••• 0121",
     "outcome": "in_stock",
     "evidenceQuote": "yes, we have two bottles of the 400 on the shelf",
     "observedAt": "2026-09-09T01:39:30.000Z",
     "holdResponse": "offered",
     "quantityNote": "two bottles",
     "restockExpectation": "",
     "basis": "this_request"
    }
   ],
   "attempts": [
    {
     "siteId": "eb-ind-3",
     "name": "Fruitvale Botica",
     "outcome": "in_stock",
     "usable": true,
     "usableReason": "verified",
     "evidenceQuote": "yes, we have two bottles of the 400 on the shelf",
     "waveIndex": 0,
     "observationId": "obs_sample_found",
     "dispatchId": "dsp_sample_f1",
     "recipientId": "rcp_sample01",
     "transcriptTurns": 8
    },
    {
     "siteId": "eb-ind-5",
     "name": "Alameda Island Pharmacy",
     "outcome": "voicemail",
     "usable": false,
     "usableReason": "voicemail",
     "evidenceQuote": "",
     "waveIndex": 0,
     "observationId": "obs_sample_vm",
     "dispatchId": "dsp_sample_f1",
     "recipientId": "rcp_sample02",
     "transcriptTurns": 0
    }
   ]
  },
  {
   "request": {
    "id": "fr_sample_human",
    "watchId": "amoxicillin-susp",
    "product": {
     "name": "amoxicillin",
     "strength": "400 mg/5 mL",
     "form": "oral suspension"
    },
    "region": "US-CA-SF",
    "need": 2,
    "waveSize": 3,
    "maxWaves": 2,
    "askHold": true,
    "status": "needs_human",
    "plannedSiteIds": [
     "sf-chn-3"
    ],
    "usedSiteIds": [
     "sf-chn-3"
    ],
    "confirmedSiteIds": [],
    "createdAt": "2026-09-08T22:04:00.000Z",
    "updatedAt": "2026-09-08T22:30:00.000Z"
   },
   "productLabel": "amoxicillin 400 mg/5 mL oral suspension",
   "waves": 1,
   "halt": {
    "dispatchId": "dsp_sample_f2",
    "waveIndex": 0,
    "state": "needs_human",
    "note": "CALL-E did not acknowledge the task within 20 minutes"
   },
   "confirmed": [],
   "attempts": [
    {
     "siteId": "sf-chn-3",
     "name": "Crescent Rx #103",
     "outcome": "unknown",
     "usable": false,
     "usableReason": "recipient_in_progress",
     "evidenceQuote": "",
     "waveIndex": 0,
     "observationId": "obs_sample_prog",
     "dispatchId": "dsp_sample_f2",
     "recipientId": "rcp_sample03",
     "transcriptTurns": 0
    }
   ]
  },
  {
   "request": {
    "id": "fr_sample_exh",
    "watchId": "amoxicillin-susp",
    "product": {
     "name": "amoxicillin",
     "strength": "400 mg/5 mL",
     "form": "oral suspension"
    },
    "region": "US-CA-SJ",
    "need": 1,
    "waveSize": 3,
    "maxWaves": 2,
    "askHold": true,
    "status": "exhausted",
    "plannedSiteIds": [
     "sj-ind-2",
     "sj-ind-3"
    ],
    "usedSiteIds": [
     "sj-ind-2",
     "sj-ind-3"
    ],
    "confirmedSiteIds": [],
    "createdAt": "2026-09-08T19:10:00.000Z",
    "updatedAt": "2026-09-08T19:25:00.000Z"
   },
   "productLabel": "amoxicillin 400 mg/5 mL oral suspension",
   "waves": 2,
   "halt": null,
   "confirmed": [],
   "attempts": [
    {
     "siteId": "sj-ind-2",
     "name": "Alum Rock Family Rx",
     "outcome": "out_of_stock",
     "usable": true,
     "usableReason": "verified",
     "evidenceQuote": "we're completely out",
     "waveIndex": 0,
     "observationId": "obs_sample_ex1",
     "dispatchId": "dsp_sample_f3",
     "recipientId": "rcp_sample04",
     "transcriptTurns": 6
    },
    {
     "siteId": "sj-ind-3",
     "name": "Japantown Drug",
     "outcome": "ivr_dead_end",
     "usable": false,
     "usableReason": "ivr_only",
     "evidenceQuote": "",
     "waveIndex": 1,
     "observationId": "obs_sample_ex2",
     "dispatchId": "dsp_sample_f4",
     "recipientId": "rcp_sample05",
     "transcriptTurns": 3
    }
   ]
  }
 ],
 "audit": [
  {
   "at": "2026-09-09T23:43:41.649Z",
   "entity": "dispatch",
   "entityId": "dsp_82df1750c0b52fe3",
   "from": "terminal_unverified",
   "to": "terminal_verified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "entity": "dispatch",
   "entityId": "dsp_82df1750c0b52fe3",
   "from": "accepted",
   "to": "terminal_unverified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.640Z",
   "entity": "dispatch",
   "entityId": "dsp_2f8a742954992b2b",
   "from": "terminal_unverified",
   "to": "terminal_verified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.638Z",
   "entity": "dispatch",
   "entityId": "dsp_2f8a742954992b2b",
   "from": "accepted",
   "to": "terminal_unverified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.631Z",
   "entity": "dispatch",
   "entityId": "dsp_aff38507be46b2e3",
   "from": "terminal_unverified",
   "to": "terminal_verified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.629Z",
   "entity": "dispatch",
   "entityId": "dsp_aff38507be46b2e3",
   "from": "accepted",
   "to": "terminal_unverified",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.628Z",
   "entity": "dispatch",
   "entityId": "dsp_82df1750c0b52fe3",
   "from": "reserved",
   "to": "accepted",
   "note": null
  },
  {
   "at": "2026-09-09T23:43:41.627Z",
   "entity": "dispatch",
   "entityId": "dsp_82df1750c0b52fe3",
   "from": null,
   "to": "reserved",
   "note": null
  }
 ],
 "events": [
  {
   "at": "2026-09-09T23:43:41.640Z",
   "event": {
    "type": "observation",
    "observationId": "obs_97139b41dab5550d",
    "siteId": "sf-ind-1",
    "siteName": "Mission Family Pharmacy",
    "outcome": "unreachable",
    "usable": false,
    "usableReason": "recipient_failed",
    "evidenceQuote": "",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.640Z",
   "event": {
    "type": "observation",
    "observationId": "obs_3ba9b9c88cb4306e",
    "siteId": "sj-chn-2",
    "siteName": "Bayline Pharmacy #102",
    "outcome": "out_of_stock",
    "usable": true,
    "usableReason": "verified",
    "evidenceQuote": "we're completely out",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.641Z",
   "event": {
    "type": "dispatch",
    "dispatchId": "dsp_2f8a742954992b2b",
    "state": "terminal_verified",
    "callId": "call_fake_11d69879485d",
    "kind": "sweep",
    "siteIds": [
     "sf-chn-2",
     "sf-chn-4",
     "sf-chn-1",
     "sf-ind-2",
     "sf-ind-1",
     "sj-chn-2"
    ],
    "note": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.646Z",
   "event": {
    "type": "estimate",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W36",
    "signal": "shortage",
    "pHat": 0.1111111111111111
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_d09651925738",
    "eventType": "call.created",
    "message": "Call task accepted.",
    "details": {
     "recipients": 4
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_7f741ef2dd0b",
    "eventType": "call.dialing",
    "message": "Dialing recipient.",
    "details": {
     "recipient_id": "rcp_a26e57a1"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_2199842d3111",
    "eventType": "call.recipient_completed",
    "message": "Out of stock; staff do not know when it will return.",
    "details": {
     "recipient_id": "rcp_a26e57a1",
     "scenario": "out_of_stock_human"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_955d61083f5e",
    "eventType": "call.dialing",
    "message": "Dialing recipient.",
    "details": {
     "recipient_id": "rcp_2779c344"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_132953071d11",
    "eventType": "call.recipient_completed",
    "message": "Out of stock; staff do not know when it will return.",
    "details": {
     "recipient_id": "rcp_2779c344",
     "scenario": "out_of_stock_human"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_5025c1ad9ac7",
    "eventType": "call.dialing",
    "message": "Dialing recipient.",
    "details": {
     "recipient_id": "rcp_edcb19bd"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_1c5a3c017f97",
    "eventType": "call.recipient_completed",
    "message": "Out of stock; staff do not know when it will return.",
    "details": {
     "recipient_id": "rcp_edcb19bd",
     "scenario": "out_of_stock_human"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_cb0fd4361d66",
    "eventType": "call.dialing",
    "message": "Dialing recipient.",
    "details": {
     "recipient_id": "rcp_d9dcc60d"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_daf1e86795d3",
    "eventType": "call.recipient_completed",
    "message": "Staff declined to share stock information by phone.",
    "details": {
     "recipient_id": "rcp_d9dcc60d",
     "scenario": "refused"
    }
   }
  },
  {
   "at": "2026-09-09T23:43:41.647Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_122e39d0db9a",
    "eventId": "evt_bc0fca278b1a",
    "eventType": "call.completed",
    "message": "4 of 4 recipients reached pharmacy staff.",
    "details": {}
   }
  },
  {
   "at": "2026-09-09T23:43:41.648Z",
   "event": {
    "type": "observation",
    "observationId": "obs_0bf1112eefb77300",
    "siteId": "sj-chn-3",
    "siteName": "Crescent Rx #103",
    "outcome": "out_of_stock",
    "usable": true,
    "usableReason": "verified",
    "evidenceQuote": "we're completely out",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.648Z",
   "event": {
    "type": "observation",
    "observationId": "obs_c18490630086c2c1",
    "siteId": "sj-ind-3",
    "siteName": "Japantown Drug",
    "outcome": "out_of_stock",
    "usable": true,
    "usableReason": "verified",
    "evidenceQuote": "we're completely out",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.649Z",
   "event": {
    "type": "observation",
    "observationId": "obs_3584dd89bdd88245",
    "siteId": "sj-ind-6",
    "siteName": "Almaden Valley Rx",
    "outcome": "out_of_stock",
    "usable": true,
    "usableReason": "verified",
    "evidenceQuote": "we're completely out",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.649Z",
   "event": {
    "type": "observation",
    "observationId": "obs_d53e344c2f00dd53",
    "siteId": "sj-ind-1",
    "siteName": "Willow Glen Pharmacy",
    "outcome": "refused",
    "usable": false,
    "usableReason": "refused",
    "evidenceQuote": "we can't give out stock information over the phone",
    "source": "sweep",
    "watchId": "amoxicillin-susp",
    "findRequestId": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.649Z",
   "event": {
    "type": "dispatch",
    "dispatchId": "dsp_82df1750c0b52fe3",
    "state": "terminal_verified",
    "callId": "call_fake_122e39d0db9a",
    "kind": "sweep",
    "siteIds": [
     "sj-chn-3",
     "sj-ind-3",
     "sj-ind-6",
     "sj-ind-1"
    ],
    "note": null
   }
  },
  {
   "at": "2026-09-09T23:43:41.655Z",
   "event": {
    "type": "estimate",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W36",
    "signal": "shortage",
    "pHat": 0.08333333333333333
   }
  },
  {
   "at": "2026-09-09T23:43:41.660Z",
   "event": {
    "type": "estimate",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W36",
    "signal": "shortage",
    "pHat": 0.08333333333333333
   }
  },
  {
   "at": "2026-09-09T23:43:41.661Z",
   "event": {
    "type": "sweep",
    "sweepId": "swp_ca0e8fea902593dc",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W36",
    "status": "complete",
    "note": "all planned sites reconciled"
   }
  },
  {
   "at": "2026-09-08T22:04:00.000Z",
   "event": {
    "type": "find",
    "findRequestId": "fr_sample_human",
    "status": "running",
    "confirmed": 0,
    "need": 2
   }
  },
  {
   "at": "2026-09-08T22:04:01.000Z",
   "event": {
    "type": "dispatch",
    "dispatchId": "dsp_sample_f2",
    "state": "reserved",
    "callId": null,
    "kind": "find",
    "siteIds": [
     "sf-chn-3"
    ],
    "note": null
   }
  },
  {
   "at": "2026-09-08T22:30:00.000Z",
   "event": {
    "type": "dispatch",
    "dispatchId": "dsp_sample_f2",
    "state": "needs_human",
    "callId": null,
    "kind": "find",
    "siteIds": [
     "sf-chn-3"
    ],
    "note": "CALL-E did not acknowledge the task within 20 minutes"
   }
  },
  {
   "at": "2026-09-08T22:30:01.000Z",
   "event": {
    "type": "find",
    "findRequestId": "fr_sample_human",
    "status": "needs_human",
    "confirmed": 0,
    "need": 2
   }
  },
  {
   "at": "2026-09-09T01:38:31.000Z",
   "event": {
    "type": "dispatch",
    "dispatchId": "dsp_sample_f1",
    "state": "accepted",
    "callId": "call_fake_sample01",
    "kind": "find",
    "siteIds": [
     "eb-ind-3",
     "eb-ind-5"
    ],
    "note": null
   }
  },
  {
   "at": "2026-09-09T01:38:32.000Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_sample01",
    "eventId": "evt_sample_created",
    "eventType": "call.created",
    "message": "Call task accepted.",
    "details": {
     "recipients": 2
    }
   }
  },
  {
   "at": "2026-09-09T01:38:40.000Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_sample01",
    "eventId": "evt_sample_dial1",
    "eventType": "call.dialing",
    "message": "Dialing recipient.",
    "details": {
     "recipient_id": "rcp_sample01"
    }
   }
  },
  {
   "at": "2026-09-09T01:39:30.000Z",
   "event": {
    "type": "observation",
    "observationId": "obs_sample_found",
    "siteId": "eb-ind-3",
    "siteName": "Fruitvale Botica",
    "outcome": "in_stock",
    "usable": true,
    "usableReason": "verified",
    "evidenceQuote": "yes, we have two bottles of the 400 on the shelf",
    "source": "find",
    "watchId": "amoxicillin-susp",
    "findRequestId": "fr_sample_met"
   }
  },
  {
   "at": "2026-09-09T01:39:31.000Z",
   "event": {
    "type": "observation",
    "observationId": "obs_sample_vm",
    "siteId": "eb-ind-5",
    "siteName": "Alameda Island Pharmacy",
    "outcome": "voicemail",
    "usable": false,
    "usableReason": "voicemail",
    "evidenceQuote": "",
    "source": "find",
    "watchId": "amoxicillin-susp",
    "findRequestId": "fr_sample_met"
   }
  },
  {
   "at": "2026-09-09T01:39:35.000Z",
   "event": {
    "type": "call_event",
    "callId": "call_fake_sample01",
    "eventId": "evt_sample_done",
    "eventType": "call.completed",
    "message": "All recipients handled.",
    "details": {}
   }
  },
  {
   "at": "2026-09-09T01:39:40.000Z",
   "event": {
    "type": "find",
    "findRequestId": "fr_sample_met",
    "status": "met",
    "confirmed": 1,
    "need": 1
   }
  },
  {
   "at": "2026-09-09T01:40:00.000Z",
   "event": {
    "type": "estimate",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W37",
    "signal": "insufficient_data",
    "pHat": 1.0
   }
  },
  {
   "at": "2026-09-09T01:45:00.000Z",
   "event": {
    "type": "sweep",
    "sweepId": "swp_sample37",
    "watchId": "amoxicillin-susp",
    "isoWeek": "2026-W37",
    "status": "waiting",
    "note": "16 site(s) outside their local calling window; they will be dialled on a later run"
   }
  },
  {
   "at": "2026-09-09T01:45:01.000Z",
   "event": {
    "type": "notice",
    "level": "warn",
    "message": "sweep: nothing dispatched, every planned site is outside its calling window"
   }
  }
 ]
};
